Tweak Completion Description
SeedCompany/cord-field pull request #1086
Opened 2022-01-24 20:31 UTC by daniel-leod

Fixes #928

2022-01-24 20:42 UTC, CarsonF reviewed
Isn't this already how it works?

2022-01-24 22:21 UTC, daniel-leod commented
@CarsonF Just tested on https://dev.cordfield.com/ and latest version of `develop`. This is how it looks:
![image](https://user-images.githubusercontent.com/36520121/150865572-33ca04bb-351c-4877-a6f6-838de3bf0b40.png)

2022-01-24 23:16 UTC, CarsonF requested changes

2022-01-24 23:16 UTC, CarsonF commented on src/scenes/Products/Detail/ProductInfo.tsx
> +    wordWrap: 'break-word',
It looks like this is deprecated.
It suggests to use this instead:
```css
overflow-wrap: break-word;
```

2022-01-25 00:59 UTC, CarsonF approved these changes

2022-01-25 00:59 UTC, merged