Update organization name
SeedCompany/cord-field pull request #1107
Opened 2022-04-21 16:38 UTC by zkhin

### Actual
![image](https://user-images.githubusercontent.com/4212008/164509021-8039a0d3-2e41-43c6-9587-1ff13db55e89.png)

2022-04-21 17:40 UTC, CarsonF requested changes

2022-04-21 17:40 UTC, CarsonF commented on .yarn/build-state.yml
> +# Warning: This file is automatically generated. Removing it is fine, but will
You can delete this file, it's no longer used.

2022-04-21 17:40 UTC, CarsonF commented on src/scenes/Partners/Edit/EditPartner.tsx
> +        if (organizationName && partner.organization.value) {
The org name will always be truthy, even if it's not changed. You should check if this field is dirty instead. Here are some examples:
https://github.com/SeedCompany/cord-field/blob/f6001e70a1c304d64ef20ad30be88a7ae68645ec/src/scenes/Products/Edit/EditProduct.tsx#L259-L267
https://github.com/SeedCompany/cord-field/blob/f6001e70a1c304d64ef20ad30be88a7ae68645ec/src/scenes/Engagement/EditEngagement/EditEngagementDialog.tsx#L275-L281

2022-04-22 17:46 UTC, zkhin commented
@CarsonF Give me some minutes, I am resolving the type error on my end.

2022-04-22 22:29 UTC, CarsonF approved these changes

2022-04-22 22:30 UTC, merged