Make Products Changeset Aware
SeedCompany/cord-field pull request #1142
Opened 2022-07-08 16:00 UTC by elisabeth-sorrell

API PR: https://github.com/SeedCompany/cord-api-v3/pull/2471

2022-07-08 16:02 UTC, elisabeth-sorrell commented
<img width="1235" alt="Screen Shot 2022-07-08 at 11 02 29 AM" src="https://user-images.githubusercontent.com/15220335/178028939-0d7bdc91-ba51-4622-93ce-d28b36cf42b1.png">

2022-07-08 16:06 UTC, elisabeth-sorrell commented
- Having a little styling problems with the badge outline not stretching to the icon when a prop is changed...
- Not sure if this is part of the scope, but the languageEngagement where the products are added to doesn't have a changeset badge with changed mode.
- Also not sure what to do with the title for a Product with Other type. Should that also have a changeset badge? should it be even changeset aware in the first place?



Also note that I put icons on the right instead of the left. I thought it went better with the flow of how the props are displayed, instead of changing margins on a changeset (the icon overlaps the label when it's on the left.)

2022-08-16 15:57 UTC, CarsonF requested changes
Looking good!

Will you rebase this on develop? I think you'll just have some MUI & React imports to adjust.

I need to study the ChangesetPropList component more.

2022-08-16 15:57 UTC, CarsonF commented on src/common/fragments/changeset.graphql
> +fragment OtherProductProps on OtherProduct {
```suggestion
  ... on OtherProduct {
```

2022-08-16 15:57 UTC, CarsonF commented on src/components/Changeset/ChangesetBadge.tsx
> +          // Assuming more info is given when changedå
```suggestion
          // Assuming more info is given when changed
```

2022-08-16 15:57 UTC, CarsonF commented on src/scenes/Products/Create/CreateProduct.tsx
> +      navigate(`/engagements/${changesetId ? mergedId : engagementId}`);
```suggestion
      navigate(`/engagements/${mergedId}`);
```

2022-08-16 15:57 UTC, CarsonF commented on src/components/Changeset/ChangesetBadge.tsx
> +  anchorHorizontal?: 'right' | 'left';
I'd prefer to be more consistent with upstream prop
```suggestion
  anchorOrigin?: Partial<BadgeOrigin>;
```
```ts
anchorOrigin={{ horizontal: 'right' }}
```

2022-08-16 19:26 UTC, CarsonF commented on src/components/Changeset/ChangesetPropList.tsx
> +    return;
```suggestion
    return null;
```
to make component ReactNode compatible

2022-08-16 21:14 UTC, elisabeth-sorrell commented on src/components/Changeset/ChangesetPropList.tsx
> +    return;
done

2024-08-15 00:57 UTC, sethmcknight commented
This lived to the end of its lifetime and died

2024-08-15 00:57 UTC, closed without merging