Vscode graphql updates
SeedCompany/cord-field pull request #1438
Opened 2023-05-02 20:36 UTC by willdch

Added a `.graphqlrc.yaml` file needed for the recommended Graphql extensions to give better Graphql `syntax highlighting`, `auto-completion` and `go to definition` support.

2023-05-02 20:49 UTC, CarsonF reviewed
Extrapolate review requests from here please
https://github.com/SeedCompany/seed-api/pull/428

2023-07-12 01:41 UTC, CarsonF requested changes

2023-07-12 01:41 UTC, CarsonF commented on .env
> +CORD_URL=https://api.dev.cordfield.com
Don't add another env var for the same purpose. The one below this is fine. 

```suggestion
```

2023-07-12 01:41 UTC, CarsonF commented on .graphqlrc.yaml
> +documents: src/**/*.graphql
```suggestion
documents: src/**/*.graphql

```

2024-08-15 00:59 UTC, sethmcknight commented
This lived to the end of its lifetime and died

2024-08-15 00:59 UTC, closed without merging