Partner Engagements tab max width
SeedCompany/cord-field pull request #1533
Opened 2024-06-06 17:59 UTC by rdonigian

https://seed-company-squad.monday.com/boards/5989610236/views/132288519/pulses/6786242569

2024-06-06 18:08 UTC, CarsonF requested changes

2024-06-06 18:08 UTC, CarsonF commented on src/scenes/Partners/Detail/PartnerDetail.tsx
> +      <Paper sx={{ maxWidth: filters.tab === 'engagements' ? 'auto' : 'lg' }}>
I'd rather not do this. It breaks the open/close principle.
Can we do
```ts
<Paper sx={(theme) => ({
  '--maxWidth': theme.breakpoints.values.lg,
  maxWidth: 'var(--maxWidth)',
}}
```
And in the engagements tab
```ts
sx={{
  ':root': {
    '--maxWidth': 'initial',
  }
}}
```

2024-06-06 18:43 UTC, CarsonF commented
Does this work?

2024-06-06 19:50 UTC, rdonigian commented
It seemed like it but after a second glance apparently all the tabs are getting set to full width, so just working through on how to properly address it.

2024-06-07 12:38 UTC, CarsonF commented
It appears that this wouldn't work like I was thinking it would. I think we need to shift the `<Paper>` down to each tab. I originally moved it up here to keep it DRY, but not we can't customize.
I took the opportunity to fix this and a handful of other things on this page: #1535

2024-06-07 16:15 UTC, closed without merging

2024-06-07 16:16 UTC, rdonigian commented
This is been solved by https://github.com/SeedCompany/cord-field/pull/1535