Rich text posts
SeedCompany/cord-field pull request #892
Opened 2021-07-15 19:50 UTC by richardgirges

This is the first draft of rich text editing with CK Editor.

Things to note:
* This PR contains PR #889 and should be rebased after 889 is merged

* There are no typings for the React CKEditor wrapper. The type check is failing right now because of this. [Lack of typings for CKEditor is a long-standing issue with no solid resolution as of yet](https://github.com/ckeditor/ckeditor5/issues/504). Please advise on how to approach

2021-07-15 20:47 UTC, CarsonF commented
> * There are no typings for the React CKEditor wrapper. The type check is failing right now because of this. [Lack of typings for CKEditor is a long-standing issue with no solid resolution as of yet](https://github.com/ckeditor/ckeditor5/issues/504). Please advise on how to approach


We've got a few libraries we provide our own types for in the `typings` folder. It looks like there are types in DefinitelyTyped for the core of the library, so really we just need to provide connection points to this library. Should be trivial since both referenced are thin wrappers.

2021-07-19 21:12 UTC, CarsonF commented on src/components/posts/PostListItemCard/PostListItemCard.tsx
> +              {parse(props.body.value || '')}
We should probably memoize this, eh?

2021-07-19 21:20 UTC, CarsonF approved these changes
Looks good @richardgirges!

2021-08-09 21:09 UTC, CarsonF requested changes
The CKE features should be limited to only those we can render. I'd remove quotes, tables, pics, and video.

We should style the output with `react-html-parser` and the display inside of the editor to be consistent with our theme.

2021-08-09 21:09 UTC, CarsonF commented on src/components/posts/PostListItemCard/PostListItemCard.tsx
> +            <Typography variant="body2">{postBody}</Typography>
Currently this puts any html tags under a `<p>` tag which is invalid HTML.

2021-11-09 17:38 UTC, ParkeBrown commented
@daniel-leod can you confirm that we still need to address the unresolved comment above?

2021-11-09 22:20 UTC, daniel-leod commented
> @daniel-leod can you confirm that we still need to address the unresolved comment above?

@ParkeBrown I think the last commit would resolve that. This PR is ready for review.

2021-11-11 20:44 UTC, ParkeBrown commented
Daniel believes he's covered the requested changes

2022-07-07 20:19 UTC, CarsonF commented
I'd like to go with an editor that produces JSON instead, instead of html string. So rendering can be easily customized based on context.

2022-07-07 20:19 UTC, closed without merging