Add preset inventory UI
SeedCompany/cord-field pull request #942
Opened 2021-09-14 14:16 UTC by zkhin

### UI
- Project Detail page
![image](https://user-images.githubusercontent.com/4212008/133274138-d7978f2f-dec7-47c7-b90b-faabeed68d1f.png)

- Project Card
![image](https://user-images.githubusercontent.com/4212008/133274305-3d9830cc-95fe-4307-ab51-cb3b512c629d.png)

- Language Detail page
![image](https://user-images.githubusercontent.com/4212008/133274391-dc582ec0-ac79-49d9-9e02-81068c066a24.png)

Preset Inventory filter option is added to Project & Language filters.

2021-09-14 14:18 UTC, zkhin commented
@CarsonF I am getting this console warning.
![image](https://user-images.githubusercontent.com/4212008/133274622-3219eb17-f61e-4c63-a2ee-81e44042ca21.png)

Seems like there's an issue in the provided SVG files [here](https://github.com/SeedCompany/cord-api-v3/pull/2086#issuecomment-915371797).

2021-09-14 14:30 UTC, zkhin commented on src/scenes/Projects/Overview/ProjectOverview.tsx
> +              <Tooltip title="This indicates the project/language(s) will be exposed to major investors to directly fund.">
Instead of having a new component under the `Projects` directory, added the preset inventory icon directly into the detail component.

2021-09-14 16:01 UTC, CarsonF requested changes

2021-09-14 16:01 UTC, CarsonF commented on src/scenes/Languages/Detail/LanguageDetail.tsx
> +                <IconButton className={classes.presetInventoryIcon}>
Not a button here, only an icon. I'd probably just only show the filled icon if true and omit if false.

2021-09-14 16:03 UTC, CarsonF commented
> Seems like there's an issue in the provided SVG files [here](https://github.com/SeedCompany/cord-api-v3/pull/2086#issuecomment-915371797).

Looks like the server is emitted the filled icon but then the client uses the outlined icon. Maybe a loading state issue?

2021-09-14 21:14 UTC, zkhin commented
> > Seems like there's an issue in the provided SVG files [here](https://github.com/SeedCompany/cord-api-v3/pull/2086#issuecomment-915371797).
> 
> Looks like the server is emitted the filled icon but then the client uses the outlined icon. Maybe a loading state issue?

Resolved now.

2021-09-16 01:07 UTC, CarsonF approved these changes

2021-09-16 01:07 UTC, merged